name: Extract Route Data

on:
  workflow_dispatch: # Allow manual runs

jobs:
  extract-routes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install cheerio

      - name: Extract routes
        run: node fetch-routes-list.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/routes.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update: Extracted route data"
          git push
